// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['beatify']['App']['AddConnection'](arg1);
}

export function IsExistConnection() {
  return window['go']['beatify']['App']['IsExistConnection']();
}
