// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['beatify']['App']['AddConnection'](arg1);
}

export function CreateDir(arg1) {
  return window['go']['beatify']['App']['CreateDir'](arg1);
}

export function DeleteDir(arg1) {
  return window['go']['beatify']['App']['DeleteDir'](arg1);
}

export function GetAllDirs() {
  return window['go']['beatify']['App']['GetAllDirs']();
}

export function GetPlayNextList(arg1, arg2, arg3) {
  return window['go']['beatify']['App']['GetPlayNextList'](arg1, arg2, arg3);
}

export function GetSong(arg1) {
  return window['go']['beatify']['App']['GetSong'](arg1);
}

export function GetSongs(arg1, arg2) {
  return window['go']['beatify']['App']['GetSongs'](arg1, arg2);
}

export function IsExistConnection() {
  return window['go']['beatify']['App']['IsExistConnection']();
}

export function PlayNext(arg1, arg2, arg3, arg4) {
  return window['go']['beatify']['App']['PlayNext'](arg1, arg2, arg3, arg4);
}

export function PlayPrev(arg1, arg2, arg3, arg4) {
  return window['go']['beatify']['App']['PlayPrev'](arg1, arg2, arg3, arg4);
}

export function ReSyncDir(arg1) {
  return window['go']['beatify']['App']['ReSyncDir'](arg1);
}

export function StartServer() {
  return window['go']['beatify']['App']['StartServer']();
}

export function UpdateDir(arg1, arg2) {
  return window['go']['beatify']['App']['UpdateDir'](arg1, arg2);
}

export function UpdateSong(arg1, arg2) {
  return window['go']['beatify']['App']['UpdateSong'](arg1, arg2);
}
