// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {beatify} from '../models';

export function AddConnection(arg1:string):Promise<beatify.Response>;

export function IsExistConnection():Promise<beatify.Response>;
