// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['beatify']['App']['AddConnection'](arg1);
}

export function CreateDir(arg1) {
  return window['go']['beatify']['App']['CreateDir'](arg1);
}

export function DeleteDir(arg1) {
  return window['go']['beatify']['App']['DeleteDir'](arg1);
}

export function GetAllDirs() {
  return window['go']['beatify']['App']['GetAllDirs']();
}

export function IsExistConnection() {
  return window['go']['beatify']['App']['IsExistConnection']();
}

export function UpdateDir(arg1, arg2) {
  return window['go']['beatify']['App']['UpdateDir'](arg1, arg2);
}
